// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_P511OviVWa8fCZ5SpMA5qwMkDKTd4I',
    appId: '1:175002313861:android:51b00d526adaaaed2db5ec',
    messagingSenderId: '175002313861',
    projectId: 'orbit-app-145b9',
    storageBucket: 'orbit-app-145b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA608S6aCvhE3FLo8Lk6C2KRBXzeNJbUmc',
    appId: '1:175002313861:ios:1921f4ed811dd8a12db5ec',
    messagingSenderId: '175002313861',
    projectId: 'orbit-app-145b9',
    storageBucket: 'orbit-app-145b9.appspot.com',
    iosClientId: '175002313861-ge3782bkp10ug6qrj04qf8aa5jj06uji.apps.googleusercontent.com',
    iosBundleId: 'com.example.ryanPujoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA608S6aCvhE3FLo8Lk6C2KRBXzeNJbUmc',
    appId: '1:175002313861:ios:1921f4ed811dd8a12db5ec',
    messagingSenderId: '175002313861',
    projectId: 'orbit-app-145b9',
    storageBucket: 'orbit-app-145b9.appspot.com',
    iosClientId: '175002313861-ge3782bkp10ug6qrj04qf8aa5jj06uji.apps.googleusercontent.com',
    iosBundleId: 'com.example.ryanPujoApp',
  );
}
