// Mocks generated by Mockito 5.3.2 from annotations
// in ryan_pujo_app/test/user/infrastructure/user_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ryan_pujo_app/core/infrastructure/remote_response.dart' as _i2;
import 'package:ryan_pujo_app/user/infrastructure/datasource/user_remote_datasource_contract.dart'
    as _i3;
import 'package:ryan_pujo_app/user/infrastructure/user_dto.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteResponse_0<T> extends _i1.SmartFake
    implements _i2.RemoteResponse<T> {
  _FakeRemoteResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRemoteDatasourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDatasourceContract extends _i1.Mock
    implements _i3.UserRemoteDatasourceContract {
  @override
  _i4.Future<_i2.RemoteResponse<_i5.UserDto>> registerUser(_i5.UserDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [dto],
        ),
        returnValue: _i4.Future<_i2.RemoteResponse<_i5.UserDto>>.value(
            _FakeRemoteResponse_0<_i5.UserDto>(
          this,
          Invocation.method(
            #registerUser,
            [dto],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RemoteResponse<_i5.UserDto>>.value(
                _FakeRemoteResponse_0<_i5.UserDto>(
          this,
          Invocation.method(
            #registerUser,
            [dto],
          ),
        )),
      ) as _i4.Future<_i2.RemoteResponse<_i5.UserDto>>);
  @override
  _i4.Future<_i2.RemoteResponse<_i5.UserDto>> getByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByUsername,
          [username],
        ),
        returnValue: _i4.Future<_i2.RemoteResponse<_i5.UserDto>>.value(
            _FakeRemoteResponse_0<_i5.UserDto>(
          this,
          Invocation.method(
            #getByUsername,
            [username],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RemoteResponse<_i5.UserDto>>.value(
                _FakeRemoteResponse_0<_i5.UserDto>(
          this,
          Invocation.method(
            #getByUsername,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.RemoteResponse<_i5.UserDto>>);
  @override
  _i4.Future<_i2.RemoteResponse<List<_i5.UserDto>>> getUsers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i4.Future<_i2.RemoteResponse<List<_i5.UserDto>>>.value(
            _FakeRemoteResponse_0<List<_i5.UserDto>>(
          this,
          Invocation.method(
            #getUsers,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RemoteResponse<List<_i5.UserDto>>>.value(
                _FakeRemoteResponse_0<List<_i5.UserDto>>(
          this,
          Invocation.method(
            #getUsers,
            [],
          ),
        )),
      ) as _i4.Future<_i2.RemoteResponse<List<_i5.UserDto>>>);
  @override
  _i4.Future<_i2.RemoteResponse<_i6.Unit>> update(_i5.UserDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [dto],
        ),
        returnValue: _i4.Future<_i2.RemoteResponse<_i6.Unit>>.value(
            _FakeRemoteResponse_0<_i6.Unit>(
          this,
          Invocation.method(
            #update,
            [dto],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RemoteResponse<_i6.Unit>>.value(
                _FakeRemoteResponse_0<_i6.Unit>(
          this,
          Invocation.method(
            #update,
            [dto],
          ),
        )),
      ) as _i4.Future<_i2.RemoteResponse<_i6.Unit>>);
  @override
  _i4.Future<_i2.RemoteResponse<_i6.Unit>> delete(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [username],
        ),
        returnValue: _i4.Future<_i2.RemoteResponse<_i6.Unit>>.value(
            _FakeRemoteResponse_0<_i6.Unit>(
          this,
          Invocation.method(
            #delete,
            [username],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RemoteResponse<_i6.Unit>>.value(
                _FakeRemoteResponse_0<_i6.Unit>(
          this,
          Invocation.method(
            #delete,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.RemoteResponse<_i6.Unit>>);
}
